### ISSUE TITLE
Client error

### ISSUE THREAD

**Issue by dehboris** [ovh/php-ovh-sms#1]
J'ai cet erreur quand je tente d'avoir les informations sur mon compte.
"Client error response [url] https://api.ovh.com/1.0/sms [status code] 403 [reason phrase] Forbidden" on line 89 of /Developer/www/octobercms/smsaplpha/plugins/dcolsay/sms/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php

**Comment by yadutaf** [comment]
Bonjour,

Merci d'avoir pris le temps de remonter ce problème. Pouvez vous donner un exemple de code minimal permettant de reproduire ce problème ?

**Comment by dehboris** [comment]
``` php
$Sms = new SmsApi( $applicationKey, $applicationSecret, $endpoint, $consumerKey );

// Get available SMS accounts
$accounts = $Sms->getAccounts(true);
print_r($accounts);
```

Mais les paramètres de la requête on été récupéré sur le site de ovh.

**Comment by dehboris** [comment]
J'ai aussi essayer sans  `true` dans le paramètres de la fonction `getAccounts()`
Et sa m'a donnée la même erreur.

**Comment by golgeek** [comment]
Bonjour,

Les erreurs 403 sont retournées par l'API d'OVH quand les credentials sont invalides.
Nous venons de patcher le code de la méthode getAccounts() pour qu'elle appelle l'API avec un path plus en adéquation avec la politique de credentials.

Pouvez-vous réessayer avec la nouvelle version ?

Et, si vous rencontrez toujours une erreur, pouvez-vous essayer de regénérer vos credentials sur cette URL : https://api.ovh.com/createToken/index.cgi?GET=/sms/*&PUT=/sms/*&DELETE=/sms/*&POST=/sms/*

**Comment by kefahB** [comment]
Bonjour,
J'ai le même erreur ! et j'ai essayé de changer les credentials comme vous avez indiqué mais, je fait u $sms->getAccounts() et ca retourn bien le compte sms, mais dès que je fait setAccount() ou autre ca retourne le code suivant :

Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error response [url] https://api.ovh.com/1.0/sms/sms-******-1 [status code] 403 [reason phrase] Forbidden' in /home/-*****_-/www/send_sms/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89 Stack trace: #0 /home/-**_**_-/www/send_sms/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php(33): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response)) #1 /home/-**_**_-/www/send_sms/vendor/guzzlehttp/guzzle/src/Event/Emitter.php(109): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete') #2 /home/-**_**_-/www/send_sms/vendor/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent)) #3 /home/-**_**_-/www/send_sms/vendor/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction)) #4 /home/-**_**_-/ww in /home/-**_***-/www/send_sms/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 89

j'ai testé sur les deux 
https://api.ovh.com/createToken/index.cgi?GET=/sms/&PUT=/sms/&DELETE=/sms/&POST=/sms/
et 
https://api.ovh.com/createToken/index.cgi?GET=/sms/*&PUT=/sms/*&DELETE=/sms/*&POST=/sms/*

**Comment by kgaut** [comment]
Bonjour, 
Même problème qu'au dessus, la méthode getAccounts me retourne bien le compte, mais quand j'utilise la méthode setAccount, j'ai l'exception suivante : 

`GuzzleHttp\Exception\ClientException : Client error response [url] https://api.ovh.com/1.0/sms/sms-*********-1 [status code] 403 [reason phrase] Forbidden dans GuzzleHttp\Exception\RequestException::create() (ligne 89 dans /media/vhosts/.../www/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php).`

**Comment by yadutaf** [comment]
Bonjour @kgaut 

Avez-vous essayé de ré-générer les tokens avec https://api.ovh.com/createToken/index.cgi?GET=/sms/*&PUT=/sms/*&DELETE=/sms/*&POST=/sms/* ?

**Comment by yadutaf** [comment]
Pouvez-vous eggallement essayer avec la dernière version sur Github ? Merci.

**Comment by kgaut** [comment]
Bonjour,

J'utilise la version master de votre dépot, voici mon fichier composer : 

```
{
  "name": "Mon app",
  "description": "Mon app vendor libs",
  "require": {
    "ovh/php-ovh-sms": "dev-master"
  }
}
```

merci de votre réponse rapide, j'attends que mon client me regénère des clé via le second lien pour voir ce que cela donne. Si c'est vraiment ça il faudrait mettre cette page de documentation à jour : https://www.ovh.com/fr/g1639.envoyer_des_sms_avec_lapi_ovh_en_php#mise_en_place_de_lenvironnement_creation_des_identifiants

Je vous tiens au courant dès que j'ai les nouvelles clées.

**Comment by yadutaf** [comment]
Parfait. J'ai remonté votre feedback concernant le guide. Un petit refresh lui ferait le plus grand bien.

**Comment by kefahB** [comment]
Bonjour à tous,
Je n'ai pas lu toutes les messages, mais il faut faire attention lors de la
création de Credantials de bien s'assuré que la duré est illimité, si non
votre code fonctionnera une journée puis s’arrête car les credantials
expire sous 24h je pense.

Le 29 juin 2016 à 17:13, Kevin Gautreau notifications@github.com a écrit :

> Bonjour,
> 
> J'utilise la version master de votre dépot, voici mon fichier composer :
> 
> {
>   "name": "Mon app",
>   "description": "Mon app vendor libs",
>   "require": {
>     "ovh/php-ovh-sms": "dev-master"
>   }
> }
> 
> merci de votre réponse rapide, j'attends que mon client me regénère des
> clé via le second lien pour voir ce que cela donne. Si c'est vraiment ça il
> faudrait mettre cette page de documentation à jour :
> https://www.ovh.com/fr/g1639.envoyer_des_sms_avec_lapi_ovh_en_php#mise_en_place_de_lenvironnement_creation_des_identifiants
> 
> Je vous tiens au courant dès que j'ai les nouvelles clées.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/ovh/php-ovh-sms/issues/1#issuecomment-229388232, or mute
> the thread
> https://github.com/notifications/unsubscribe/ARTstu2T9CFq3O_8FWekS3eNJuOltxJvks5qQouqgaJpZM4H4nkg
> .

## 

BADER ALDIN Kefah
PHENICIA S.A.R.L
5, Rue André Duchscher
L-1424 Luxembourg
Portable : 661 46 66 20 / 21
Fixe : 27 84 86 00
Fax: 27 84 86 01
www.phenicia.lu
phenicia@pt.lu
kefah.bader@gmail.com

**Comment by kgaut** [comment]
Bonjour,

c'est tout bon avec les clés générées via votre lien.

Merci et bonne fin de journée.

Kevin

**Comment by yadutaf** [comment]
Super. Merci pour ton feedback. Je vais garder l'issue ouverte le temps que le guide soit corrigé.

**Comment by kgaut** [comment]
Bonjour, cela a fonctionné un temps, puis j'ai eu à nouveau le message d'erreur 

`Client error response [url] https://api.ovh.com/1.0/sms/ [status code] 403 [reason phrase] Forbidden`

Qui semble correspondre à un problème de clé, dans le doute j'ai pensé que je n'avais pas fais attention à la validité des clés. J'en ai donc recréé de nouvelles en mettant bien cette fois une validité "illimitée". Cela à tout de suite fonctionné (c'était lundi matin) ce matin, je teste à nouveau, et le même message d'erreur :

`Client error response [url] https://api.ovh.com/1.0/sms/ [status code] 403 [reason phrase] Forbidden`

N'y aurait-il pas un problème de validité non prise en compte ? (je peux vous donner mes credentials par pm si besoin.

**Comment by yadutaf** [comment]
Que donne un appel sur https://api.ovh.com/console/#/auth/currentCredential#GET avec les nouveaux credentials ? Cet appel d'API permet de connaitre les autorisations attachés aux clés en cours d'utilisation.

**Comment by kgaut** [comment]
```
GuzzleHttp\Exception\ClientException : Client error response [url] https://api.ovh.com/1.0/auth/currentCredential [status code] 403 [reason phrase] Forbidden dans GuzzleHttp\Exception\RequestException::create()
```

**Comment by yadutaf** [comment]
Hum, I suspect the application is still using outdated credentials. I've generated new unlimited credentials on https://api.ovh.com/createToken/index.cgi?GET=/sms&GET=/sms/*&PUT=/sms/*&DELETE=/sms/*&POST=/sms/* and then called `GET /auth/currentCredential`. I got this response:

```
{u'applicationId': 1234,
 u'creation': u'2016-07-06T12:07:11+02:00',
 u'credentialId': 1234,
 u'expiration': None,
 u'lastUse': None,
 u'ovhSupport': False,
 u'rules': [{u'method': u'GET', u'path': u'/sms'},
  {u'method': u'GET', u'path': u'/sms/*'},
  {u'method': u'POST', u'path': u'/sms/*'},
  {u'method': u'PUT', u'path': u'/sms/*'},
  {u'method': u'DELETE', u'path': u'/sms/*'}],
 u'status': u'validated'}
```

**Comment by kgaut** [comment]
C'est ce que j'ai fais par deux, fois, en vérifiant bien le deuxième coup que je n'avais pas de limite de validité. Ça marche, au départ, puis lors de nouveaux tests le lendemain / surlendemain, cela ne passe plus et je tombe sur cette erreur 403.

**Comment by yadutaf** [comment]
Cela semble concerner l'authentification de l'API et non pas directement ce SDK PHP. Pouvez-vous poursuivre la discussion sur api@ml.ovh.net. Vous pouvez vous inscrire en envoyant un mail à api-subscribe@ml.ovh.net.

**Comment by kgaut** [comment]
Je viens d'envoyer un mail à la liste, merci de votre aide.

**Comment by cmeheut** [comment]
Bonjour, je viens d'installer le SDK, de tomber sur la même erreur:
Client error response [url] https://api.ovh.com/1.0/sms/sms-xxxxxxxxx [status code] 403 [reason phrase] Forbidden
la méthode getAccounts me retourne bien mon compte mais la méthode setAccount renvoit cette erreur.
J'ai recréé un jeu de clés/secret/consumer key mais le problème demeure. Est-ce que quelqu'un a réussi à faire fonctionner?
Merci pour votre aide

**Comment by kgaut** [comment]
tu as bien utilisé cette adresse pour générer ton jeu de clés : 

https://api.ovh.com/createToken/index.cgi?GET=/sms/*&PUT=/sms/*&DELETE=/sms/*&POST=/sms/*

?

**Comment by cmeheut** [comment]
Je suis allé sur ce formulaire:
https://eu.api.ovh.com/createToken/

**Comment by kgaut** [comment]
Oui donc le soucis vient de là sur cette page, les champs d'autorisations ne sont pas renseignés : 
![2016-07-11-17 49 12-screenshot](https://cloud.githubusercontent.com/assets/736910/16737076/02d3471e-4790-11e6-87d6-c85c2106e343.png)

À comparer avec le lien que j'ai donné plus haut. Essayes donc de regénérer tes clés avec ce lien : 

https://api.ovh.com/createToken/index.cgi?GET=/sms/*&PUT=/sms/*&DELETE=/sms/*&POST=/sms/*

**Comment by cmeheut** [comment]
Merci, je valide, je n'avais saisi la nuance entre les 2 formulaires. Bonne soirée

**Comment by yadutaf** [comment]
@cmeheut tu peux en dire plus sur la manière dont tu es arrivé sur https://eu.api.ovh.com/createToken/ sans les bonnes autorisations ? Je vais mettre à jour la doc pour ce soit plus clair :)

**Comment by cmeheut** [comment]
C'est le lien qui est présent sur cette page: https://www.ovh.com/fr/g1639.envoyer_des_sms_avec_lapi_ovh_en_php

**Comment by yadutaf** [comment]
Merci @cmeheut ! J'ai fait un sort à cette page. Le fix arrivera en production d'ici quelques minutes.
