### ISSUE TITLE
SMS divisé en plusieurs

### ISSUE THREAD

**Issue by kgaut** [ovh/php-ovh-sms#11]
Par deux fois, sur une 20aine de tests, j'ai eu mon message envoyé tronqué en 3 voir 4 sms. Certes, mon SMS dépassait les 160 caractères, mais il est marqué dans la doc qu'à part coûter plusieurs crédits, cela ne pose pas de soucis.

La dernière fois que cela s'est produit la chaîne faisait 223 caractères et a été répartie sur 4 sms, qui ne sont même pas arrivé dans le bon ordre. J'ai beau regarder, je ne vois pas de caractères spéciaux qui pourraient entraîner un problème surtout que la plupart du temps, avec la même chaîne, le sms arrive en un seul morceau.

Avez-vous une idée d'où cela pourrait provenir ?

Merci

**Comment by yadutaf** [comment]
Bonjour,

Ce comportement semble concerner le service SMS lui même et non pas le SDK PHP. Je vous invite à contacter le support technique afin qu'ils puissent regarder en détail ce qui se passe.
