### ISSUE TITLE
Tagger une version

### ISSUE THREAD

**Issue by MarceauKa** [ovh/php-ovh-sms#15]
Salut!

Je viens de mettre en ligne un paquet pour Laravel utilisant l'API OVH (https://github.com/AkibaTech/laravel-ovh-sms).

Il s'avère que mon paquet (taggé en 1.1.0) require **ovh/php-ovh-sms** en "dev-master".
A moins de mettre toute son install Laravel en "minimum-stability": "dev" (ou alors je sais pas comment faire), il est impossible de require mon package Laravel (la stabilité par défaut de Laravel empêchant les @dev).

Auriez-vous une piste ?
Sinon je forke php-ovh-sms et je le tag en 1.0 mais c'est pas cool.

Merci :)

**Comment by VincentCasse** [comment]
Oh non, pas de fork pour un tag :)

On vient d'ajouter une première release :) Dis moi si ca te débloque

**Comment by MarceauKa** [comment]
Super ! Merci :)
