### ISSUE TITLE
Paquet Laravel 5

### ISSUE THREAD

**Issue by MarceauKa** [ovh/php-ovh-sms#3]
Bonjour !

Seriez-vous intéressé par l'intégration d'un plugin pour Laravel 5 ?
Il pourrait être directement intégré sous un namespace Ovh\Sms\Laravel.

Si oui, je pourrais contribuer en cela :)

**Comment by dehboris** [comment]
Oui, J'ai eu la même idée et je bosse déjà actuellement sur sa.

**Comment by VincentCasse** [comment]
Salut Akiba,

Je pense que ce type d'intégration sera toujours appréciée :)
N'hésitez pas à les remonter ici même.

Cordialement

**Comment by yadutaf** [comment]
Hello,

comme il s'agit pas vraiment d'un bug, je ferme l'issue. N'hésitez pas à soumettre une PR !

**Comment by MarceauKa** [comment]
@yadutaf @VincentCasse Le paquet Laravel 5 est en place :)
Si jamais vous souhaitez le linker dans le readme.

https://github.com/AkibaTech/laravel-ovh-sms
